@hostname = https://home.passwordless.com.au:3115/webauth




post {{hostname}}/registerOrg
Content-Type: application/json

{
    "name":"nitesh",
    "username" : "nitesh"
}
###
post {{hostname}}/createApp
Content-Type: application/json

{
    "name":"test",
    "origin" : "https://home.passwordless.com.au:3115",
    "orgId":"lFQN8laTyn6fORu4DVtmr"
}

###
delete {{hostname}}/deleteApp/9Iv78-dUcK2CnjKC-bLKf1GehKq4kUOk

###
get {{hostname}}/getAllApplications/lFQN8laTyn6fORu4DVtmr


###
post {{hostname}}/generateEmailToken
Content-Type: application/json

{
    "username" : "nite0sh@gmail.com",
    "appId" : "1234ihcndcs"
}

###

post {{hostname}}/verifyToken
Content-Type: application/json

{
  "accessToken": "onjtYYde35sHIoX7uPBJ52sxN"
}


###

post {{hostname}}/createSubDomain
Content-Type: application/json

{
    "name" : "bluebricks"
}


###

post {{hostname}}/sendmail
Content-Type: application/json

{
    "sendTo" : "nitesh@mollatech.com",
    "type" : "activation",
    "name" : "Nitesh Singh",
    "link" : "https://www.google.com"
}



###
get {{hostname}}/checkSubdomain/test