@hostname = http://localhost:3005/webauth




post {{hostname}}/registerUser
Content-Type: application/json

{
    "username" : "nitesh"
}
###
post {{hostname}}/createApp
Content-Type: application/json

{
    "name":"test",
    "origin" : "http://localhost:3005",
    "orgId":"lFQN8laTyn6fORu4DVtmr"
}

###
delete {{hostname}}/deleteApp/9Iv78-dUcK2CnjKC-bLKf1GehKq4kUOk

###
get {{hostname}}/getAllApplications/lFQN8laTyn6fORu4DVtmr


###
post {{hostname}}/generateEmailToken
Content-Type: application/json

{
    "username" : "nite0sh@gmail.com",
    "appId" : "1234ihcndcs"
}

###

post {{hostname}}/verifyToken
Content-Type: application/json

{
  "accessToken": "onjtYYde35sHIoX7uPBJ52sxN"
}


###

post {{hostname}}/createSubDomain
Content-Type: application/json

{
    "name" : "bluebricks"
}