export const CREATE_SUBDOMAIN_REQUEST = "CREATE_SUBDOMAIN_REQUEST";
export const CREATE_SUBDOMAIN_SUCCESS = "CREATE_SUBDOMAIN_SUCCESS";
export const CREATE_SUBDOMAIN_FAILURE = "CREATE_SUBDOMAIN_FAILURE";